
// This file has been generated by the GUI designer. Do not modify.
namespace SpineGTK_v1
{
	public partial class RemoveGameWindow
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button btnDelete;

		private global::Gtk.Button btnCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SpineGTK_v1.RemoveGameWindow
			this.Name = "SpineGTK_v1.RemoveGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Remove Game");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SpineGTK_v1.RemoveGameWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnDelete = new global::Gtk.Button();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseStock = true;
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = "gtk-delete";
			this.fixed2.Add(this.btnDelete);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnDelete]));
			w1.X = 312;
			w1.Y = 300;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.fixed2.Add(this.btnCancel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCancel]));
			w2.X = 230;
			w2.Y = 300;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 393;
			this.DefaultHeight = 344;
			this.Show();
			this.btnDelete.Clicked += new global::System.EventHandler(this.OnBtnDeleteClicked);
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
		}
	}
}
