
// This file has been generated by the GUI designer. Do not modify.
namespace SpineGTK_v1
{
	public partial class AddGameWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label lblGameName;

		private global::Gtk.Label lblGameDirectory;

		private global::Gtk.Entry entry2;

		private global::Gtk.Button btnEnter1;

		private global::Gtk.Button btnCancel1;

		private global::Gtk.Button btnInstallSpine;

		private global::Gtk.Entry entry1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SpineGTK_v1.AddGameWindow
			this.Name = "SpineGTK_v1.AddGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Add Game");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child SpineGTK_v1.AddGameWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.fixed1.Add(this.fixed2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fixed2]));
			w1.X = 264;
			w1.Y = 21;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblGameName = new global::Gtk.Label();
			this.lblGameName.Name = "lblGameName";
			this.lblGameName.LabelProp = global::Mono.Unix.Catalog.GetString("Game Name:");
			this.fixed1.Add(this.lblGameName);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblGameName]));
			w2.X = 6;
			w2.Y = 8;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblGameDirectory = new global::Gtk.Label();
			this.lblGameDirectory.Name = "lblGameDirectory";
			this.lblGameDirectory.LabelProp = global::Mono.Unix.Catalog.GetString("Game Directory:");
			this.fixed1.Add(this.lblGameDirectory);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblGameDirectory]));
			w3.X = 6;
			w3.Y = 43;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed1.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
			w4.X = 119;
			w4.Y = 39;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEnter1 = new global::Gtk.Button();
			this.btnEnter1.CanFocus = true;
			this.btnEnter1.Name = "btnEnter1";
			this.btnEnter1.UseStock = true;
			this.btnEnter1.UseUnderline = true;
			this.btnEnter1.Label = "gtk-ok";
			this.fixed1.Add(this.btnEnter1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEnter1]));
			w5.X = 352;
			w5.Y = 277;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancel1 = new global::Gtk.Button();
			this.btnCancel1.CanFocus = true;
			this.btnCancel1.Name = "btnCancel1";
			this.btnCancel1.UseStock = true;
			this.btnCancel1.UseUnderline = true;
			this.btnCancel1.Label = "gtk-cancel";
			this.fixed1.Add(this.btnCancel1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancel1]));
			w6.X = 271;
			w6.Y = 277;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnInstallSpine = new global::Gtk.Button();
			this.btnInstallSpine.CanFocus = true;
			this.btnInstallSpine.Name = "btnInstallSpine";
			this.btnInstallSpine.UseUnderline = true;
			this.btnInstallSpine.Label = global::Mono.Unix.Catalog.GetString("Install Spine");
			this.fixed1.Add(this.btnInstallSpine);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnInstallSpine]));
			w7.X = 1;
			w7.Y = 282;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w8.X = 119;
			w8.Y = 7;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 307;
			this.Show();
			this.btnEnter1.Clicked += new global::System.EventHandler(this.OnBtnEnter1Clicked);
			this.btnCancel1.Clicked += new global::System.EventHandler(this.OnBtnCancel1Clicked);
			this.btnInstallSpine.Clicked += new global::System.EventHandler(this.OnBtnInstallSpineClicked);
		}
	}
}
